# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
data = [
    {
        name: "Oladushky (Honey Yeast Blini)",
        description: "For Russians, blini is the symbol for the sun and its ability to warm the Earth and give life. Sticking with that theme, these tasty treats are Russian pancakes that are dressed with honey or jam and sure to warm you up on a chilly day.",
        image_url: "https://images.britcdn.com/wp-content/uploads/2017/12/Blinis-3.jpg?blur=2&auto=format&q=10",
        ingredients: "500 ml/2 cups kefir, 1 egg, 2 tbsp sugar, 1/2 tsp salt, 350 g/2 1/4 cup all purpose flour, 1/2 tsp baking soda, powdered sugar",
        instructions: "1. In a large bowl mix kefir, an egg, sugar and salt with a whisk. 2. In a separate bowl mix flour and baking soda. Add the wet ingredients to the dry ones and stir to combine. The batter will be thick! 3. Let it sit for 15 minutes without stirring. 4. Heat a non-stick pan with enough oil to cover the bottom of the pan up to 1 cm/1/3 inch deep. Drop kefir pancakes with a large spoon or a small ice-cream scoop into hot oil and fry on one side until golden and the batter is cooked halfway through, then flip carefully taking care not to splash hot oil. Use two spatulas if necessary. The pancakes will puff up as soon as you flip them over. Maintain medium heat to ensure each pancake is cooked all the way through as they are going to be tall. (Add oil throughout the frying process as needed.) 5. Serve dusted with powdered sugar, whipped cream or smetana/creme fraiche and fresh fruit."
    },
    {
        name: "Shuba (Herring Under Fur Coat)",
        description: "Shuba, which translates to herring under fur, can be an acquired taste, but once you’re used to the flavor of herring, this beautifully colored salad is a treat at the table. This uniquely named Russian dish is made with cooked beets, carrots, potatoes, and boiled eggs dressed with mayonnaise. Just make sure to use herring that's not pickled in cream.",
        image_url: "https://images.britcdn.com/wp-content/uploads/2017/12/Shuba-Salad.jpg?blur=2&auto=format&q=10",
        ingredients: "3 large potatoes, 4 large carrots, 3 large beets, 1 1/2 cups mayonnaise, 1 medium red onion (finely chopped), 4 fillets of pickled herring in oil (finely chopped), 4 large hard-boiled eggs (finely chopped), Black pepper to taste, Garnish: parsley or dill",
        instructions: "1. Gather the ingredients. 2. In a large saucepan, bring 3 quarts of water to a boil and add the beets. After 20 minutes, add the potatoes and 20 minutes later add the carrots. The ingredients will all cook in the same pot at different speeds but will all be tender after approximately 1 hour. Add more boiling water from a kettle if needed. Drain and let cool for 10 minutes before handling. 3. While still warm, peel the potatoes, carrots, and beets. Set aside to cool completely. 4. Shred the carrots and beets, and finely chop the potatoes. Do not mix the ingredients but place in separate bowls. 5. On a pretty serving platter, place a ring mold or the ring from a springform pan. This salad can also be assembled free form in a round or oval shape or in a 13 x 9 pan. 6. Place all of the chopped potatoes in the ring, covering the bottom. Pat carefully into an even layer. Spread 1/3 of the mayonnaise to completely cover the potatoes. 7. Place half of the beets in a thin layer, and then half of the carrots. Finally, place half of the finely chopped onion, creating distinctive layers in the process. 8. Use all of the chopped pickled herring to cover the beets, carrots, and onions and use another 1/3 of the mayonnaise to cover up this thick layer. 9. Layer the rest of the onion and carrots, and all of the chopped eggs. Add black pepper to taste. Cover with what's left of the mayonnaise and beets. Carefully pack down so there's nothing else showing but bright beets. 10. Refrigerate for at least 6 hours. When the time to serve comes, carefully remove the ring, if using, so the layers of the salad are shown. If using the extra hardboiled eggs, slice them and place them on top of the salad to decorate it. Garnish with chopped dill. 11. Serve and enjoy!"
    },
    {
        name: "Russian Okroshka (Cold Summer Soup)",
        description: "This soup is comfort food for hot days. (Yes, that's a thing that exists.) Cold, tart, and crunchy, it's loaded with fresh vegetables that make it refreshing and good for you too. Because the base is made from sour cream and egg, it's also extra filling, which can be welcome on those days when you’re hungry but have absolutely no desire to turn on the oven.",
        image_url: "https://images.britcdn.com/wp-content/uploads/2017/12/IMG_7423.jpg?blur=2&auto=format&q=10",
        ingredients: "8 cups cold water, 1/3 cup sour cream, 3 1/2 Tbsp Vinegar divided, 2 1/2 tsp Salt, 3 Tbsp chopped dill (fresh or frozen), 1/2 cup green onion, finely chopped, 1/2 ham diced, 3-4 medium cooked potatoes, peeled and diced, 3 hard-boiled eggs, diced,3-4 cucumbers, diced",
        instructions: "1. Peel potatoes and dice them into 1/4″ cubes. Place diced potatoes in a medium pot and cover with water. Add 1 Tbsp vinegar and bring to a boil then continue boiling for 10 minutes or until the potatoes are cooked, but not falling apart. Drain well and set aside to cool. For quicker cooling, you can rinse potatoes with cold water. 2. While potatoes are cooking , boil 3 eggs and cooled them in ice water. Here is the link to make perfect boiled eggs. 3. Next, dice 3 eggs, 3-4 cucumbers, and 1/2 lb of ham. Also chop 3 Tbsp of dill and 1/2 cup of green onions. Place everything in a large pot. 4. In a separate large bowl, whisk together 8 cups of cold water, 1/3 cup of sour cream, 2 1/2 Tbsp of vinegar, 2 1/2 tsp of salt until combined.  Pour the mixture in the pot with the rest of ingredients. Stir to combine and serve."
    },
    {
        name: "Russian Red Borscht",
        description: "Although borscht is known for featuring beets, it's actually a vibrant soup filled with a variety of vegetables and sometimes meat. Every family makes their borscht slightly differently, but most are served with a traditional dollop of sour cream on top. You can also choose to serve this soup hot or cold.",
        image_url: "https://images.britcdn.com/wp-content/uploads/2017/12/IMG_1481.jpg?blur=2&auto=format&q=10",
        ingredients: "For Borscht: 3 medium beets peeled and grated, 4 Tbsp olive oil divided, 4 cups reduced sodium chicken broth + 6 cups water, 3 medium yukon potatoes peeled and sliced into bite-sized pieces, 2 carrots peeled and thinly sliced.  For Zazharka (Mirepoix):2 celery ribs trimmed and finely chopped, 1 small red bell pepper finely chopped, optional, 1 medium onion finely chopped, 4 Tbsp ketchup or 3 Tbsp tomato sauce",
        instructions: "1. Peel, grate and/or slice all vegetables, keeping sliced potatoes in cold water until ready to use. 2. Heat a large soup pot (5 1/2 Qt or larger) over medium/high heat and add 2 Tbsp olive oil. Add grated beets and sauté 10 minutes, stirring occasionally until beets are softened. 3. Add 4 cups broth and 6 cups water. Add sliced potatoes and sliced carrots then cook for 10-15 minutes or until easily pierced with a fork. 4. While potatoes are cooking, place a large skillet over medium/high heat and add 2 Tbsp oil. Add chopped onion, celery and bell pepper. Saute stirring occasionally until softened and lightly golden (7-8 minutes). Add 4 Tbsp Ketchup and stir fry 30 seconds then transfer to the soup pot to continue cooking with the potatoes. 5. When potatoes and carrots reach desired softness, add 1 can of beans with their juice, 2 bay leaves, 2-3 Tbsp white vinegar, 1 tsp salt, 1/4 tsp black pepper, 1 pressed garlic clove, and 3 Tbsp chopped dill. Simmer for an additional 2-3 minutes and add more salt and vinegar to taste."
    },
    {
        name: "Olivie (Russian Salad)",
        description: "Think of this as potato salad with extra vegetables thrown in. The best part of this easy chopped salad is that it uses ingredients that are pantry staples. Originally, the dish incorporated cooked, wild meat, but now most people use bologna or some other type of sausage meat.",
        image_url: "https://images.britcdn.com/wp-content/uploads/2017/12/Russian-Salad-Olivie-6.jpg?blur=2&auto=format&q=10",
        ingredients: "3/4 lb meat, cubed / 3 potatoes, cooked and cubed / 3 carrots, cooked and cubed / 6 eggs, cooked and cubed / 3 dill pickles, cubed / 1 sweet onion, cubed / 1 cup frozen fresh peas / 1/2 english cucumber, cubed / 1 cup mayo / dill to taste / salt and pepper, to taste / 1/2 tsp sugar, optional",
        instructions: "1. In a large pot, add potatoes and carrots. Cover completely with water. Bring to a boil and cook about 20-25 minutes or until a knife pierces through easily. (Don’t overcook. Remove carrots and potatoes from water, set aside to cool). 2. In a small pot, add eggs, cover eggs will water and bring to a boil cook. Cook eggs 8-10 minutes. 3. Cube all of the ingredients. 4. Combine everything, mix. Add mayo to taste. You may need a little more than 1 cup, depending on sizes of your ingredients. 5. Season with salt, pepper and sugar. Add fresh dill, mix. "
    },
    {
        name: "Kulebyaka (Russian Pie)",
        description: "This complex pie is often made with several layers that can include a few types of ground meat or fish, eggs, rice, cabbage, and mushrooms, before it's encased in a pastry dough and elaborately decorated. It's a great choice for indecisive eaters because each slice contains all the layers for a very flavorful — and very varied — meal.",
        image_url: "https://images.britcdn.com/wp-content/uploads/2017/12/8928924301_191a903607_b.jpg?blur=2&auto=format&q=10",
        ingredients: "Ingredients for Easy Kulebyaka Dough: 1 cup milk lukewarm / ¼ cup water lukewarm / 3 eggs plus 1 egg yolk for egg wash / 3 tablespoons melted butter / 4½ cups of flour / 2 teaspoons sugar / 1 teaspoon salt / 2¼ teaspoons yeast or 7g packet of yeast / Ingredients for Kulebyaka filling: 900 g 2lbs Salmon pieces, boneless skinless / 1 large onion diced / 1 cup uncooked rice / 1 bunch of dill finely chopped / salt and pepper to taste / 2 tablespoons butter",
        instructions: "1. Place ingredients, in the order listed, into your bread machine and select the dough program. Should take about 90 minutes to complete the dough cycle. 2. Wash and cook the rice according to directions. Fluff with a fork and set aside and allow to cool. 3. In a frying pan, heat 3 tablespoons of butter on high, and fry the onions until they are opaque and just starting to brown, no more than 5 minutes. Add to the rice and mix together. Add the chopped dill, salt and pepper, mix and set aside. 4. Chop the salmon into chunky bite size pieces, or what size you prefer. Add salt and pepper and set aside. 5. On a floured surface, remove the dough from the bread maker (it will be sticky) and quickly knead for about 30 seconds, removing the air bubbles in the dough, and making it less sticky and ready to roll. Cut the dough in half. Roll out a dough piece into a large rectangle around 7mm or thick enough to cover your baking sheet. To transfer the dough to your baking sheet, carefully fold the dough into 3-4 pieces and place inside your baking sheet. 6. Place the rice lengthways down the centre of the dough, making a rectangle rice shape. Leave a clean edge of dough to allow the dough to seal. Top with salmon pieces, spread evenly over the rice. Cut 2 tablespoons of butter into small pieces and place randomly across the salmon. 7. Roll out the 2nd piece of dough and place over top of the salmon, it will resemble a loaf. Push the edges together to seal the dough pieces, and cut off any excess dough and set aside. 8. Using your excess dough, roll it out the same way, and use it to decorate your Kulebyaka with designs. For a lattice effect, use a lattice roller, which I don't have. Take a sharp knife and cut 3inch x 2 inch lines (vertically) with a quater gap before your next 2 inch cut starts. Start the next row of cuts where the quater inch gap is, making another 2 inch cut. Evenly space the cuts vertically, and repeat until your dough is cut. Carefully lift the lattice dough and place on top of the Kulebyaka. Gently press the ages of the dough together, only at the edges of the Kulebyaka. Do not attempt to press the lattice on the top of your pie. Cut off the excess pieces. See photo for better idea of the cuts. 9. Cover with a towel and allow to rise again for about 30 minutes. Preheat oven to 190°C/345°F. 10. Beat an egg yolk with 1 teaspoon of whipping cream (optional) and brush all over the Kulebyaka. Using a small knife, make 2 incisions on top of the Kulebyaka, or using a wooden skewer, prick 8 holes to allow steam to escape. Place in a preheated oven and bake for a total of 40 minutes. At the 15-20 minute mark, when the top is golden brown, cover with foil to prevent burning."
    },
    {
        name: "Solyanka (Rustic Smoked and Sour Soup)",
        description: "Perfect for using up leftovers, this soup combines any smoked and non-smoked meats that you may have on hand. In fact, because there are no set rules for what exact cuts of meat can go into this soup, any soup that combines a large variety of ingredients has become known as solyanka. Generally, what gives this soup its ultra smokey flavor are the hard rock variety of smoked meats like ham, salami, sausage, and bacon. Then the addition of pickles, olives, and lemon juice bring a mild tartness to the mix.",
        image_url: "https://images.britcdn.com/wp-content/uploads/2017/12/Rustic-Smoked-and-Sour-Soup-Solyanka-5.jpg?blur=2&auto=format&q=10",
        ingredients: "10 cups water / 4 tablespoons beef base / 1/2 head shredded cabbage / 1 cup chopped celery / 1 tablespoon oil / 2 medium chopped onions / 2 peeled and chopped carrots / 1 pound Polish kabanosy sausage, sliced 1/4-inch thick / 2 cooked chicken breasts, cubed / 1 cup cubed ham / 3 large chopped dill pickles / 1 small can tomato paste / 2 tablespoons capers / 3/4 cup sliced black olives / 2 cans stewed tomatoes / 1 cup dry white wine / Salt and pepper",
        instructions: "1. Add water and beef base to the soup pot and bring to a boil. Add shredded cabbage and sliced celery, return to the boil, reduce heat and simmer 30 minutes. 2. Put oil into a large skillet and heat. Add onion and carrots, and sauté until translucent. Add sausage, chicken, ham, pickles and tomato paste. Bring to a boil, reduce heat and simmer 2 minutes. Transfer to the soup pot. 3. Add capers, olives, stewed tomatoes, and bring barely to a boil. Add the wine and simmer gently for 20 minutes. 4. Ladle soup into hot bowls and garnish with sour cream and dill or pass them at the table for diners to serve themselves. 5. Accompany hot soup with multigrain bread."
    },
    {
        name: "Meat Blini With Cheese and Dill",
        description: "These juicy pockets of meaty goodness are simply crepes that are filled with meat, cheese, and dill. They're then pan-fried with a dollop of butter and served warm. Eat them with your hands or a fork. Either way, you’ll quickly understand that this succulent snack is a favorite in Russian cuisine for a reason.",
        image_url: "https://images.britcdn.com/wp-content/uploads/2017/12/Meat-Cheese-Blini-1.jpg?blur=2&auto=format&q=10",
        ingredients: "For Crepes: 4 large eggs / 2 cups milk / 1/2 tsp salt / 1/4 cup butter, melted / 2 1/4 cups all-purpose flour. For Filling: 1 pound ground beef, 85% lean / 1 medium onion, grated / 1 tbsp fresh dill / salt and pepper / 1/2 tsp garlic powder / 1 cup mozzarella cheese / additional 2 tbsp butter, for frying",
        instructions: "1. Prepare the crepes first. Place all of the ingredients into a blender: eggs, milk, butter, salt and flour. Blend for 2 to 3 minutes until the batter is smooth and lump free. Begin with 2 1/4 cups flour, add more if batter is too thin. 2. Preheat a crepe pan over medium heat and use 1/4 cup batter for each crepe. Pour the batter into the center of the pan, then tilt to spread it evenly to the edges. Cook for 1 to 2 minutes on the first side, until golden, then turn with a rubber spatula and cook on the other side for 30 seconds. Stack the crepes onto a tray. 3. Prepare the meat filling. Preheat a large saute pan over medium heat and add a drizzle of olive oil. Add the ground beef and season with approximately 1 1/2 teaspoons salt, a bit of ground black pepper and garlic powder. Fry the ground beef for 5 to 7 minutes, until well browned all over, breaking apart any larger pieces. Add the grated onion and fry for 2 to 3 more minutes, until onion is tender and fragrant. 4. In a large bowl, combine the meat mixture with grated mozzarella cheese and fresh dill. To assemble the blini, spread a few tablespoons of the filling onto the center of each crepe. Fold over the sides first, then fold into a small pocket. 5. Preheat a clean frying pan over low-medium heat and add about 1/2 tablespoon of butter for each batch. Fry the blini 3 to 4 at a time, 2 to 3 minutes per side, until golden. Serve warm with sour cream on the side."
    }
]

data.each do |recipe|
    Recipe.create(recipe)
end